apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
type: Opaque
data:
  mongo-user: bW9uZ29Vc2Vy ## les datas sont encode avec le commande suivante : echo -n text-to-encode | base64
  mongo-password: bW9uZ29QYXNzd29yZA==
